// <auto-generated />
using System;
using Intex_Group3_6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intex_Group3_6.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240410170053_legoData")]
    partial class legoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Intex_Group3_6.Models.ItemRec", b =>
                {
                    b.Property<string>("item")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("rec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("item");

                    b.ToTable("ItemRecs");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.LineItem", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.Order", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactionId"));

                    b.Property<string>("bank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryOfTransaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entryMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("fraud")
                        .HasColumnType("bit");

                    b.Property<string>("shippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("time")
                        .HasColumnType("int");

                    b.Property<float>("transactionAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("transactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("typeOfCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeOfTransaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("transactionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("category1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numParts")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("primaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("birthDate")
                        .HasColumnType("date");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.UserRec", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("rec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rec5")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("UserRecs");
                });
#pragma warning restore 612, 618
        }
    }
}
