// <auto-generated />
using System;
using Intex_Group3_6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intex_Group3_6.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240409201404_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Intex_Group3_6.Models.ItemRec", b =>
                {
                    b.Property<string>("item")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec1")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec10")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec2")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec3")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec4")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec5")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec6")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec7")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec8")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec9")
                        .HasColumnType("TEXT");

                    b.HasKey("item");

                    b.ToTable("ItemRecs");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.LineItem", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("productId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("transactionId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.Order", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("countryOfTrnsaction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dayOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("entryMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("fraud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("shippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("time")
                        .HasColumnType("INTEGER");

                    b.Property<float>("transactionAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("transactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("typeOfCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("transactionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imgLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("numParts")
                        .HasColumnType("INTEGER");

                    b.Property<float>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("primaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("secondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("birthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Intex_Group3_6.Models.UserRec", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("rec1")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec2")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec3")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec4")
                        .HasColumnType("TEXT");

                    b.Property<string>("rec5")
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("UserRecs");
                });
#pragma warning restore 612, 618
        }
    }
}
